name: Pushes new prod Docker image to the DO registry

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      SHORT_SHA: $(echo $GITHUB_SHA | head -c7)

    steps:
      - name: Checkout k8s-apps repo
        uses: actions/checkout@v2
        with:
          repository: CamelotLabs/k8s-apps
          path: k8s-apps
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Update kustomization.yml
        run: |
          cd k8s-apps/apps.camelot/prod/images/
          awk -v newTag="$SHORT_SHA" '/- name: exchange-main-worker/{found=1} found && /newTag:/{sub(/newTag: .*/, "newTag: " newTag); found=0} 1' kustomization.yml > temp.yml && mv temp.yml kustomization.yml

      - name: Commit and push changes
        run: |
          cd k8s-apps
          git config user.name "0xCaliburSigma"
          git config user.email "0xcalibursigma@protonmail.com"
          git checkout -b version-bump
          git add -A
          git commit -m "Update exchange-main-worker tag to $(echo $GITHUB_SHA | head -c7)"
          git push origin -f version-bump
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Check for existing PR from version-bump to main
        id: check-pr
        run: |
          pr_info=$(gh pr list --state open --base main --head version-bump  --json id -q '.[]')
          echo "::set-output name=id::$(echo $pr_info | jq -r '.id')"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Create PR if none exists
        if: ${{ steps.check-pr.outputs.id == '' }}
        run: |
          gh pr create --base main --head version-bump --title "Version Bump" --body "Automated version bump PR"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}